//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AccountOperation
{
	public virtual object Amount
	{
		get;
		set;
	}

	public virtual object Time
	{
		get;
		set;
	}

	public virtual Account To
	{
		get;
		set;
	}

}

