//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Application
{
	public virtual object Id
	{
		get;
		set;
	}

	public virtual object LoanAmount
	{
		get;
		set;
	}

	public virtual object TimeCreated
	{
		get;
		set;
	}

	public virtual object Term
	{
		get;
		set;
	}

	public virtual Tariff Tariff
	{
		get;
		set;
	}

	public virtual CreditPurpose CreditPurpose
	{
		get;
		set;
	}

}

