//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer
{
	public virtual object IdentificationNumber
	{
		get;
		set;
	}

	public virtual object FirstName
	{
		get;
		set;
	}

	public virtual object LastName
	{
		get;
		set;
	}

	public virtual object MiddleName
	{
		get;
		set;
	}

	public virtual object Phone
	{
		get;
		set;
	}

	public virtual object Address
	{
		get;
		set;
	}

	public virtual object Email
	{
		get;
		set;
	}

	public virtual object Personal
	{
		get;
		set;
	}

}

