//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tariff
{
	public virtual object Id
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

	public virtual object InterestRate
	{
		get;
		set;
	}

	public virtual object MinAmount
	{
		get;
		set;
	}

	public virtual object MaxAmount
	{
		get;
		set;
	}

	public virtual object CreationDate
	{
		get;
		set;
	}

	public virtual object EndDate
	{
		get;
		set;
	}

	public virtual object MinTerm
	{
		get;
		set;
	}

	public virtual object MaxTerm
	{
		get;
		set;
	}

	public virtual object IsGuarantorNeeded
	{
		get;
		set;
	}

	public virtual object MinAge
	{
		get;
		set;
	}

	public virtual object MaxAge
	{
		get;
		set;
	}

	public virtual object InitialFee
	{
		get;
		set;
	}

	public virtual object Purpose
	{
		get;
		set;
	}

	public virtual object Citizenship
	{
		get;
		set;
	}

}

