//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class Document
{
	public virtual object Id
	{
		get;
		set;
	}

	public virtual object Number
	{
		get;
		set;
	}

	public virtual Customer Customer
	{
		get;
		set;
	}

	public virtual DocType DocType
	{
		get;
		set;
	}

	public virtual TariffDocType TariffDocType
	{
		get;
		set;
	}

	public virtual IEnumerable<LoanApplication> LoanApplications
	{
		get;
		set;
	}

}

