//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class LoanService
{
	public virtual IEnumerable<Loan> Loans
	{
		get;
		set;
	}

	public virtual void CreateLoanContract()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseLoanContract()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RegisterPayment()
	{
		throw new System.NotImplementedException();
	}

}

