//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class PaymentSchedule
{
	public virtual object Id
	{
		get;
		set;
	}

	public virtual IEnumerable<Payment> Payments
	{
		get;
		set;
	}

	public virtual void AddPayment()
	{
		throw new System.NotImplementedException();
	}

}

