//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class Payment
{
	public virtual object Date
	{
		get;
		set;
	}

	public virtual object Id
	{
		get;
		set;
	}

	public virtual PaymentType PaymentType
	{
		get;
		set;
	}

}

