//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class Transaction
{
	public virtual object Id
	{
		get;
		set;
	}

	public virtual object Time
	{
		get;
		set;
	}

	public virtual object Amount
	{
		get;
		set;
	}

	public virtual Account From
	{
		get;
		set;
	}

	public virtual Account To
	{
		get;
		set;
	}

	public virtual Employee CommitedBy
	{
		get;
		set;
	}

}

