//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Account
{
	public virtual object Number
	{
		get;
		set;
	}

	public virtual object Balance
	{
		get;
		set;
	}

	public virtual object CreationDate
	{
		get;
		set;
	}

	public virtual Employee Employee
	{
		get;
		set;
	}

}

