//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AccountApi
{
	public virtual void CommitTransaction()
	{
		throw new System.NotImplementedException();
	}

	public virtual void FindTransactionById()
	{
		throw new System.NotImplementedException();
	}

	public virtual void FindTransactionsBy()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateAccount()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseAccount()
	{
		throw new System.NotImplementedException();
	}

}

