//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Loan
{
	public virtual Application Application
	{
		get;
		set;
	}

	public virtual Account Accumulator3819
	{
		get;
		set;
	}

	public virtual Account Percentages
	{
		get;
		set;
	}

	public virtual Account GeneralDebt
	{
		get;
		set;
	}

	public virtual Account Future
	{
		get;
		set;
	}

}

