//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class LoanApplication
{
	/// <summary>
	/// Application identity
	/// </summary>
	public virtual int Id
	{
		get;
		set;
	}

	/// <summary>
	/// Запрашиваемый размер кредита
	/// </summary>
	public virtual object LoanAmount
	{
		get;
		set;
	}

	public virtual object TimeCreated
	{
		get;
		set;
	}

	/// <summary>
	/// Срок, на который запрашивается кредит
	/// </summary>
	public virtual object Term
	{
		get;
		set;
	}

	public virtual Tariff Tariff
	{
		get;
		set;
	}

	public virtual LoanPurpose LoanPurpose
	{
		get;
		set;
	}

	public virtual IEnumerable<Document> Documents
	{
		get;
		set;
	}

}

