// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class LoanApplicationFull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoanApplicationFull));
        
        string IMigrationMetadata.Id
        {
            get { return "201312100010475_LoanApplicationFull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
