// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class RequireCellPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequireCellPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "201312092003240_RequireCellPhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
